name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install cmake ninja-build python3 python3-venv git \
                          lsb-release wget software-properties-common gnupg
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19 all

      - name: Set up Python virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Build
        run: |
          source venv/bin/activate
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_C_COMPILER=clang-19 \
            -DCMAKE_CXX_COMPILER=clang++-19 \
            -DCMAKE_CXX_FLAGS="-stdlib=libc++" \
            -DZIP_ENABLE_TEST=ON \
            -DZIP_ENABLE_OPT_TEST=ON \
            -DZIP_ENABLE_BENCHMARK=ON \
            -DZIP_USE_SANITIZER="Address;Undefined"
          cmake --build build
      
      - name: Code formatting
        run: |
          source venv/bin/activate
          cmake --build build --target format

      - name: Unit tests
        run: |
          source venv/bin/activate
          cmake --build build --target test
      
      - name: Optimization tests
        run: |
          source venv/bin/activate
          cmake --build build --target test-opt
